# Generated by Django 3.2.8 on 2021-11-15 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(choices=[('Не могу заргестрироваваться', 'Не могу заргестрироваваться'), ('Нет возможности забронировать автобус на нужнкю дату', 'Нет возможности забронировать автобус на нужнкю дату'), ('Не получаеться авторизоваться', 'Не получаеться авторизоваться'), ('Другие вопросы', 'Другие вопросы')], max_length=255),
        ),
    ]
