# Generated by Django 3.2.8 on 2021-11-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='room_url',
            field=models.URLField(default=None),
        ),
    ]
