# Generated by Django 3.2.8 on 2021-11-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_room_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date_added',)},
        ),
    ]
