# Generated by Django 3.2.8 on 2021-11-14 11:57

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_model', models.CharField(max_length=25, verbose_name='Марка авобуса')),
                ('bus_number', models.DecimalField(decimal_places=0, max_digits=4, verbose_name='Номер автобуса')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='SLUG')),
                ('bus_colour', models.CharField(choices=[('Красный', 'Красный'), ('Белый', 'Белый'), ('Черный', 'Черный'), ('Зеленый', 'Зеленый'), ('Синий', 'Синий'), ('Желтый', 'Желтый'), ('Серый', 'Серый'), ('Оранжевый', 'Оранжевый'), ('Голубой', 'Голубой')], max_length=25, verbose_name='Цвет автобуса')),
                ('bus_photo', models.ImageField(upload_to='media/bus/', verbose_name='Фотография автобуса')),
                ('number_sites', models.PositiveIntegerField(default=4, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(15)], verbose_name='Количество мест')),
                ('bus_rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Автобус',
                'verbose_name_plural': 'Автобусы',
                'ordering': ('-bus_rating',),
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_stop', models.CharField(max_length=25, verbose_name='Остановка')),
                ('delta_time', models.TimeField(default=datetime.time(0, 0), verbose_name='Время в пути')),
            ],
            options={
                'verbose_name': 'Остановка',
                'verbose_name_plural': 'Остановки',
            },
        ),
        migrations.CreateModel(
            name='Rout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_start', models.CharField(max_length=25, verbose_name='Начало маршрута')),
                ('name_finish', models.CharField(max_length=25, verbose_name='Конец маршрута')),
                ('slug', models.SlugField(max_length=25, unique=True, verbose_name='SLUG')),
                ('bus_stops', models.ManyToManyField(to='booking_app.BusStop', verbose_name='Остановка')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.rout')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.CreateModel(
            name='RoutesTravelDatesTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата отправления')),
                ('travel_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время отправления')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.busdetails')),
                ('rout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.rout')),
            ],
            options={
                'verbose_name': 'Отправление',
                'verbose_name_plural': 'Отправления',
                'ordering': ('-travel_date',),
            },
        ),
        migrations.CreateModel(
            name='BookingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Полная стоимость')),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Льготная стоимость')),
                ('price_baggage', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Стоимость провоза багажа')),
                ('price_rout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.rout', verbose_name='Стоимость')),
            ],
            options={
                'verbose_name': 'Цена',
                'verbose_name_plural': 'Цены',
            },
        ),
    ]
