# Generated by Django 3.2.8 on 2021-11-14 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rout',
            name='parent',
        ),
    ]
