# Generated by Django 3.2.8 on 2021-11-14 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_booked_trip', models.PositiveIntegerField(default=0)),
                ('quantity_cancel_trip', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статиска поездок',
                'verbose_name_plural': 'Статиски поездок',
                'ordering': ('-user',),
            },
        ),
        migrations.CreateModel(
            name='NewTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50, verbose_name='Контактный телефон')),
                ('quantity_adult', models.PositiveIntegerField(default=0)),
                ('quantity_child', models.PositiveIntegerField(default=0)),
                ('quantity_baggage', models.PositiveIntegerField(default=0)),
                ('price_adult', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_child', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_baggage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к поездке')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Сonfirmed', 'Сonfirmed')], default='Booked', max_length=50, verbose_name='Статус')),
                ('paid', models.CharField(choices=[('Card', 'Card'), ('Cash', 'Cash')], default='Cash', max_length=50, verbose_name='Оплата')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=4)),
                ('status_trip', models.BooleanField(default=False, verbose_name='Явка')),
                ('bus_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_app.busstop', verbose_name='Остановка посадки')),
                ('rout_data_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking_app.routestraveldatestimes', verbose_name='Дата-Время поездки')),
                ('rout_trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.rout', verbose_name='Направление')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
                'ordering': ('-user',),
            },
        ),
    ]
