# Generated by Django 3.2.8 on 2021-11-16 18:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_remove_rout_parent'),
        ('booking_bus', '0002_alter_newtrip_rout_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtrip',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='rout_data_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.routestraveldatestimes', verbose_name='Дата-Время поездки'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='user',
            field=models.CharField(default='User', max_length=50, verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='TicketTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rout_data_time', models.CharField(max_length=50, verbose_name='Дата поезки')),
                ('bus_stop', models.CharField(max_length=50, verbose_name='Остановка посадки')),
                ('time_stop', models.TimeField(default=django.utils.timezone.now, verbose_name='Время посадки')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Общая стоиомсть')),
                ('bus_info', models.CharField(max_length=50, verbose_name='Инфрмация о автобусе')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking_bus.newtrip', verbose_name='Поезка')),
            ],
        ),
    ]
