# Generated by Django 3.2.8 on 2021-11-17 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_bus', '0003_auto_20211116_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettrip',
            options={'ordering': ('-rout_data_time',), 'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AddField(
            model_name='tripsuser',
            name='quantity_default_trip',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='price_adult',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Стоимость полного билета'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='price_baggage',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Стоимость провоза багажа'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='price_child',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Стоимость льготного билета'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='quantity_adult',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Количество взрослых'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='quantity_baggage',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Количество мест для багажа'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='quantity_child',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Количество детей'),
        ),
    ]
