# Generated by Django 3.2.8 on 2021-11-20 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_bus', '0004_auto_20211118_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_bus.newtrip', verbose_name='Поезка'),
        ),
    ]
