# Generated by Django 3.2.8 on 2021-11-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking_bus', '0005_alter_tickettrip_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettrip',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='booking_bus.newtrip', verbose_name='Поезка'),
        ),
    ]
