# Generated by Django 3.2.8 on 2021-11-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_bus', '0010_alter_tripsuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripsuser',
            name='quantity_booked_trip',
        ),
        migrations.RemoveField(
            model_name='tripsuser',
            name='quantity_cancel_trip',
        ),
        migrations.AddField(
            model_name='tripsuser',
            name='quantity_autodelete_trip',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество автоматически удаленных броней'),
        ),
        migrations.AddField(
            model_name='tripsuser',
            name='quantity_delete_booked_trip',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество удаленых броней'),
        ),
        migrations.AlterField(
            model_name='tripsuser',
            name='quantity_default_trip',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество не явок'),
        ),
    ]
