# Generated by Django 3.2.8 on 2021-11-24 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_bus', '0011_auto_20211121_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='User', max_length=50, verbose_name='Имя')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('trip', models.CharField(default='User', max_length=50, verbose_name='Поезка')),
                ('bus_slug', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к поездке')),
                ('bus_rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Статиска поездок',
                'verbose_name_plural': 'Статиски поездок',
                'ordering': ('-user',),
            },
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='paid',
            field=models.CharField(choices=[('По карте', 'По карте'), ('Наличными', 'Наличными')], default='Наличными', max_length=50, verbose_name='Оплата'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='quantity_adult',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Количество взрослых'),
        ),
        migrations.AlterField(
            model_name='newtrip',
            name='status',
            field=models.CharField(choices=[('Забронировать', 'Забронировать'), ('Подтвердить', 'Подтвердить')], default='Забронировать', max_length=50, verbose_name='Статус'),
        ),
    ]
